# -*- coding: utf-8 -*-
"""Insertion sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vg4WpErDmpYbIxZKLwISIUX9k8TevuZV
"""

def insertion_sort(list):
  for i in range(1,len(list)):
    temp=list[i]
    j=i-1
    while j>=0 and temp>list[j]:
      list[j+1]=list[j]
      j-=1
    list[j+1]=temp
  return list
list=[1,9,7,5,11,16,10]
print('the sorted list:',insertion_sort(list))

def insertion_sort(list):
  for i in range(1,len(list)):
    temp=list[i]
    j=i-1
    while j>=0 and temp<list[j]:
      list[j+1]=list[j]
      j-=1
    list[j+1]=temp
  return list
list=[20,50,10,30,40]
print("The sorted list:{}".format(insertion_sort(list)))